version: '3.4'

services:
  imagegram:
    image: imagegram
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
