name: Node.Js CI/CD workflow
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
    - run: yarn lint
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - run: yarn test
